apiVersion: apps/v1
kind: Deployment
metadata:
  name: rel-dep
  labels: Prod
    app: web
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
          app: web
    spec:
      containers:
      - name: rel-dep-last
        image: gnommak/diploma_gnoma
        ports:
        - containerPort: 8080
        env:
        - name: v
          value: "0.1"