apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  labels:
    env: Release
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: azure-vote-front
        image: gnommak/diploma_gnoma:Latest
        resources:
          requests:
            cpu: 100m
            memory: 768Mi
          limits:
            cpu: 250m
            memory: 1024Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
    env: Release
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: web